name: Tests

on:
  pull_request:
    paths:
      - '**.py'
      - '**.ipynb'

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest]
      fail-fast: true
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List _temp directory before setup
      run: ls -la /home/runner/work/_temp || echo "Directory does not exist"

    - name: Setup Micromamba Python ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=${{ matrix.python-version }} --file requirements-dev.txt --channel conda-forge

    - name: List _temp directory after setup
      run: ls -la /home/runner/work/_temp || echo "Directory does not exist"

    - name: Check Micromamba Environment
      run: micromamba info

    - name: Install glidertest
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Run Tests
      run: |
        python -m pytest -v --cov=glidertest --cov-report term-missing tests/